// Local server urls
export const registerUserApi = 'http://localhost:8080/api/auth/register'
export const loginUserApi = 'http://localhost:8080/api/auth/login'
export const updateUserDetailsApi = 'http://localhost:8080/api/user/update'
export const updateUserAvatarApi = 'http://localhost:8080/api/user/update/avatar'
export const changeUserPasswordApi = 'http://localhost:8080/api/auth/change-password'
export const getAllUsersApi = 'http://localhost:8080/api/user'
export const getUserByIdApi = 'http://localhost:8080/api/user/'
export const deleteUserApi = 'http://localhost:8080/api/user/delete'
export const forgotPasswordApi = 'http://localhost:8080/api/auth/forgot-password'